- src/components/hex-background/hex-background.js
- src/components/hex-map/hex-map.js
- src/components/hex-map/style.css
- src/components/hex-map/style.scss
- src/components/planet-info/planet-info.js
- src/components/planet-info/style.scss
- src/components/sector/sector.js
- src/components/sector/style.scss
- src/components/sidebar-navigation/sidebar-navigation.js
- src/components/system/style.scss
- src/components/system/system.js
- src/utils/common.js
- src/utils/hex-generator.js
- src/utils/name-generator.js
> Sector Printables

- .prettierrc
- package-lock.json
- package.json
- public/index.html
- public/manifest.json
- src/changelog.json
- src/components/changelog/changelog.js
- src/components/changelog/style.scss
- src/components/configure/configure.js
- src/components/hex-background/hex-background.js
- src/components/hex-map/hex-map.js
- src/components/home/home.js
- src/components/movement-vector/style.scss
- src/components/planet-info/planet-info.js
- src/components/printable-sector/printable-sector.js
- src/components/sector-info/sector-info.js
- src/components/sector-sidebar/sector-sidebar.js
- src/components/sector/sector.js
- src/components/sidebar-navigation/sidebar-navigation.js
- src/components/system-info/system-info.js
- src/components/system-tooltips/system-tooltips.js
- src/components/system/style.scss
- src/components/system/system.js
- src/primitives/containers/absolute-container/index.js
- src/utils/hex-generator.js
There were two main sources for the bugginess. The first was that if the mouse was between hexagons, the vector would go away. The second was that crossing the actual movement vector would break the hover. To fix these, each hexagon is set to maximum width and has a set stroke width for the padding and the vector line now ignores pointer events.
In addition, prettier has been updated and some SEO meta tags were added to the html.
Fixes #25
> Fix Drag & Drop System Movement

- package-lock.json
- package.json
- public/index.html
- src/changelog.json
- src/components/planet-info/index.js
- src/components/planet-info/planet-info.js
- src/components/planet-info/style.scss
- src/primitives/form/dropdown/index.js
- src/primitives/form/dropdown/style.scss
- src/primitives/form/icon-input/index.js
- src/primitives/form/icon-input/style.scss
- src/primitives/other/modal/index.js
- src/primitives/other/modal/style.scss
- src/store/actions/planet.actions.js
> Editable Planet

- src/changelog.json
- src/components/sector-info/sector-info.js
- src/components/sidebar-info/sidebar-info.js
> Fix Sector Title Edit

- src/changelog.json
- src/utils/hex-generator.js
> Only short circuirt hex generator with a small viewport

- src/components/configure/configure.js
- src/components/home/home.js
- src/components/sector-info/sector-info.js
- src/components/sector-info/style.scss
- src/store/reducers/sector.reducers.js
- src/utils/__tests__/sector-generator.spec.js
- src/utils/sector-generator.js
A sector builder will start the sector at an empty state. If you configure the system to have specific dimension the builder will be initialized with that state.
> Sector Builder

- src/components/__tests__/planet-edit-modal.spec.js
- src/components/__tests__/system-edit-modal.spec.js
- src/components/planet-edit-modal/index.js
- src/components/planet-edit-modal/planet-edit-modal.js
- src/components/planet-edit-modal/style.scss
- src/components/planet-info/index.js
- src/components/planet-info/planet-info.js
- src/components/sector-info/index.js
- src/components/sector-info/sector-info.js
- src/components/sector-info/style.scss
- src/components/sector/index.js
- src/components/sector/sector.js
- src/components/sidebar-info/sidebar-info.js
- src/components/system-edit-modal/index.js
- src/components/system-edit-modal/system-edit-modal.js
- src/components/system-info/index.js
- src/components/system-info/system-info.js
- src/primitives/other/button/index.js
- src/primitives/other/button/style.scss
- src/store/selectors/planet.selectors.js
- src/store/selectors/sector.selectors.js
- src/store/selectors/system.selectors.js
- src/utils/__tests__/common.spec.js
- src/utils/common.js
Sometimes it's convenient to create a system or planet right from the list views in the sidebar. This is more of a convenience than anything since you can create systems and planets in other ways.
Resolves #68
> Quick Add Buttons

- src/store/api/local.js
- src/store/api/shared.js
- src/store/utils.js
It's been hell trying to manually test all the different possible states the app could get in with multiple data formats across local and synced data. It's time to simplify all this.
If you have a locally saved sector, do not fear because you can still log in and see your sector. If you want to make any changes, you'll have to sign up to sync it.
Resolves #78
> Retire Local Saving

- src/components/sidebar-entity/entity-attributes/entity-attributes.js
- src/components/sidebar-entity/entity-attributes/style.scss
- src/primitives/form/icon-input/index.js
- src/primitives/form/input/index.js
- src/primitives/form/input/style.scss
- src/store/reducers/entity.reducers.js
Allows you to add a description to any entity. The ability to [add notes](https://github.com/mpigsley/sectors-without-number/issues/37) is a different beast altogether. It allows for multiple notes per entity and visibility to players can be toggled.
> Entity Description

- src/constants/defaults.js
- src/init.js
- src/store/actions/entity.actions.js
- src/store/actions/sector.actions.js
- src/store/actions/sidebar-edit.actions.js
- src/store/actions/user.actions.js
- src/store/api/shared.js
- src/store/selectors/entity.selectors.js
- src/utils/__tests__/toasts.spec.js
- src/utils/entity.js
- src/utils/toasts.js
For users with more than 5 sectors you can keep them but you'll not be able to create any more from here on out. If you try to generate or save a sector an informational toast will pop up that tells you of the limit.
Resolves #72
> Limit Saved Sectors to 5

- src/changelog.json
- src/constants/entities.js
- src/primitives/other/table/index.js
- src/utils/entity-generators/planet-generator.js
> Allow Planets to be Children of Black Holes

- src/components/sector-map/sector-map.js
- src/components/sidebar/entity-navigation/entity-navigation.js
- src/components/sidebar/export-modal/export-modal.js
- src/components/sidebar/export-modal/index.js
- src/components/top-level-entity-modal/top-level-entity-modal.js
- src/constants/export-types.js
- src/lang/de.json
- src/lang/en.json
- src/lang/fr.json
- src/lang/sv.json
- src/primitives/modal/modal/index.js
- src/primitives/modal/modal/style.scss
- src/store/reducers/sector.reducers.js
- src/utils/export.js
It was an easy change just to dump the contents of the current sector into json format and download as a file. This option can be found in the the export modal (changed from print modal).
Resolves #131
> JSON Export

- functions/src/save-entities.js
- src/constants/defaults.js
> Increase Sector Limit

- src/components/navigation/index.js
- src/components/navigation/navigation.js
- src/store/reducers/entity.reducers.js
- src/store/selectors/base.selectors.js
> Navigate to Last Overview Entity List

- src/components/floating-toolbar/floating-toolbar.js
- src/components/floating-toolbar/index.js
- src/components/hex-map/index.js
- src/constants/icons.js
- src/lang/en.json
- src/store/actions/sector.actions.js
- src/store/reducers/sector.reducers.js
- src/store/selectors/base.selectors.js
- src/store/selectors/sector.selectors.js
A new option is added to the floating toolbar that switches between GM and Player modes.
Resolves #158
> GM/Player View Toggle

- package-lock.json
- package.json
- src/changelog.json
- src/components/floating-toolbar/index.js
- src/components/hex-map/index.js
- src/components/overview-list/index.js
- src/components/sector-map/index.js
- src/components/sidebar-entities/layer-sidebar/layer-form/index.js
- src/index.js
- src/store/actions/combined.actions.js
- src/store/actions/entity.actions.js
- src/store/actions/user.actions.js
- src/store/index.js
- src/store/reducers/entity.reducers.js
- src/store/reducers/layer.reducers.js
- src/store/reducers/sector.reducers.js
- src/store/reducers/sidebar.reducers.js
Using `connected-react-router` instead of `react-router-redux`.
> Upgrade Router Redux Integration

- firestore.rules
- src/changelog.json
- src/components/faction-table/style.scss
- src/components/game-routes/routes.js
- src/components/game-routes/style.scss
- src/components/overview-list/overview-list.js
- src/components/profile-modal/profile-modal.js
- src/components/sector-map/sector-map.js
- src/components/sector-map/style.scss
- src/components/sidebar-entities/default-sidebar/entity-attribute/entity-attribute.js
- src/store/actions/user.actions.js
- src/store/reducers/sector.reducers.js
- src/store/selectors/entity.selectors.js
- src/styles/_constants.scss
- src/utils/entity.js
Since the faction branch went out there have been a few lingering bugs. This branch fixes:
* The sector sidebar should always render on the right side of the screen even when you resize the view.
* Profile modal should now render when on the elements/factions page.
* PropType warning that occurred in sidebar when `visibility` object was undefined.
* Signup/login errors should now show up in the login modal.
* Factions/assets without a homebase/location do not show up in the main sector view.
> Various Bugs from Factions Feature

- src/changelog.json
- src/components/sidebar-entities/default-sidebar/default-sidebar.js
- src/components/sidebar-entities/default-sidebar/entity-attributes/entity-attributes.js
- src/components/sidebar-entities/default-sidebar/index.js
- src/components/sidebar-entities/default-sidebar/styles.module.scss
- src/store/actions/sidebar.actions.js
Quick update that allows you to add a link to a particular entity for it to render an image. The image can be hidden from your players.
> Entity Images

- src/changelog.json
- src/components/configure/configure.js
- src/components/overview-table/overview-table.js
- src/constants/entities.js
- src/lang/en.json
Even though there aren't official tables for black hole, system, and moon, the ability to add custom options here is now available.
Resolves #225
> Add Occupation & Situation to All Entities

- src/changelog.json
- src/utils/common.js
- src/utils/hex/canvas.js
If the color of a layer is invalid, it will be replaced with black and a warning will appear in the console.
Resolves #230
> Ensure Valid Colors Before Drawing Canvas

- README.md
The steps added to the ### Getting Started should better reflect the recent ui changes in firebase and add additional clarity.
> specificity + update to reflect latest firebase ui
